syntax = "proto3";

package wartweets;
option go_package = "github.com/DavidVelasquez77/202307705_LAB_SO1_1S2026/proyecto3/proto/gen/go/wartweets;wartweets";

// Mensaje que se enviará
message WarReportRequest {
  Countries country = 1;
  int32 warplanes_in_air = 2;
  int32 warships_in_water = 3;
  string timestamp = 4;
}

// Lista de los únicos posibles países aceptados por el proyecto
enum Countries {
  countries_unknown = 0;
  usa = 1;
  rus = 2;
  chn = 3;
  esp = 4;
  gtm = 5;
}

// Respuesta del servidor
message WarReportResponse {
  string status = 1;
}

// Servicio gRPC
service WarReportService {
  rpc SendReport (WarReportRequest) returns (WarReportResponse);
}