services:
  valkey:
    image: valkey/valkey:7.2
    container_name: valkey_so1
    ports:
      - "6379:6379"
    restart: unless-stopped

  json_api:
    image: python:3.12-alpine
    container_name: json_api
    working_dir: /data
    # Servidor simple para exponer los JSON generados por el daemon
    command: sh -c "python3 -m http.server 8080"
    volumes:
      - /home/vela/Documentos/SOPES1/PROYECTO2/daemon:/data:ro
    ports:
      - "8080:8080"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_so1
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - valkey
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    volumes:
      - grafana_data:/var/lib/grafana

# Definición del volumen para persistencia de datos de Grafana
volumes:
  grafana_data: