services:
  valkey:
    image: valkey/valkey:7.2
    container_name: valkey_so1
    ports:
      - "6379:6379"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_so1
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - valkey
