apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: rust-api-hc
  namespace: proyecto3
spec:
  default:
    config:
      type: TCP
      tcpHealthCheck:
        port: 8080
  targetRef:
    group: ""
    kind: Service
    name: rust-api
