apiVersion: v1
kind: Service
metadata:
  name: valkey-vm
  namespace: proyecto3
spec:
  publishNotReadyAddresses: true
  selector:
    kubevirt.io/vm: valkey-vm
  ports:
    - name: valkey
      port: 6379
      targetPort: 6379
      protocol: TCP
  type: ClusterIP
