apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq-pubsub
  namespace: proyecto3
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: connectionString
      value: "amqp://guest:guest@rabbitmq.proyecto3.svc.cluster.local:5672/"
scopes:
  - go-dapr-publisher
  - go-dapr-subscriber
