apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-ingest
  namespace: proyecto3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-ingest
  template:
    metadata:
      labels:
        app: go-ingest
    spec:
      imagePullSecrets:
      - name: zot-login
      containers:
        - name: go-api-rest
          image: 136.113.143.168:5000/proyecto3/go-ingest:dev
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: GO_INGEST_PORT
              value: "8081"
            - name: GRPC_WRITER_ADDR
              value: "go-writer.proyecto3.svc.cluster.local:50051" 
          ports:
            - containerPort: 8081
        - name: grpc-client
          image: 136.113.143.168:5000/proyecto3/go-ingest:dev
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: GO_INGEST_PORT
              value: "8082" 
            - name: GRPC_WRITER_ADDR
              value: "go-writer.proyecto3.svc.cluster.local:50051"
---
apiVersion: v1
kind: Service
metadata:
  name: go-ingest
  namespace: proyecto3
spec:
  selector:
    app: go-ingest
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP