apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api
  namespace: proyecto3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      imagePullSecrets:
      - name: zot-login
      containers:
        - name: rust-api
          image: 136.113.143.168:5000/proyecto3/rust-api:dev
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          env:
            - name: RUST_API_PORT
              value: "8080"
            - name: GO_INGEST_URL
              value: "http://go-ingest.proyecto3.svc.cluster.local:8081/internal/report"
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rust-api
  namespace: proyecto3
spec:
  selector:
    app: rust-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rust-api
  namespace: proyecto3
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rust-api
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 30